# Generated by Django 3.2.7 on 2022-03-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_mech', '0003_related_info_related_info'),
        ('security_mech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createsecuritymechanism',
            name='docId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_mech.createfile'),
        ),
        migrations.AlterField(
            model_name='createsecuritymechanism',
            name='level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
