# Generated by Django 3.2.7 on 2022-03-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_mech', '0003_related_info_related_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'sent'), (2, 'in_review'), (3, 'approved'), (4, 'rejected')], default=1, max_length=2)),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replication_mech.department')),
                ('docId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_mech.createfile')),
            ],
        ),
    ]
