# Generated by Django 3.2.7 on 2022-03-26 04:18

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_mech', '0005_createfile_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('replication_mech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replication_mech.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='send_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, size=8)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replication_mech.department')),
                ('send_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replication_mech.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(choices=[(1, 'sent'), (2, 'in_review'), (3, 'approved'), (4, 'rejected')], default=1, max_length=2)),
                ('departmentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='replication_mech.department')),
                ('docId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='file_mech.createfile')),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='send_doc',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replication_mech.status'),
        ),
    ]
