# Generated by Django 3.2.7 on 2022-03-26 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('replication_mech', '0002_auto_20220326_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_doc',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='replication_mech.department'),
        ),
        migrations.AlterField(
            model_name='send_doc',
            name='send_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='replication_mech.department'),
        ),
    ]
