# Generated by Django 3.2.7 on 2022-03-26 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_mech', '0005_createfile_created_by'),
        ('replication_mech', '0003_auto_20220326_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_doc',
            name='docId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docId', to='file_mech.createfile'),
        ),
    ]
