# Generated by Django 3.2.7 on 2022-03-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_mech', '0003_related_info_related_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createfile',
            old_name='file',
            new_name='doc_file',
        ),
    ]
