# Generated by Django 3.2.7 on 2022-03-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_mech', '0005_createfile_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createfile',
            name='status',
        ),
    ]
